### ISSUE TITLE
Test command feature checklist

### ISSUE THREAD

**Issue by brzpegasus** [brzpegasus/ember-cli-node-webkit#23]
Items related to `ember nw:test` that should be addressed before releasing:

* [x] Ensure test failures are correctly logged with all the failure details (#18)
* [x] When running the test command, generate all assets to a directory under `tmp` rather than working from `dist` (to mirror the behavior of `ember test`). (#19)
* [x] Reorganize the addon files to reduce the number of blueprint files. Basically, hide away the stuff that users shouldn't need to touch (#19, #20)
* [x] Verify `ember nw:test` can be run on Travis (#21)
* [x] Add tests for the `nw:test` command
* [x] Add some kind of interactive mode to run the tests in a NW.js environment without exiting the process when tests complete (#24) @sedouard 
* [x] Add a filter option to run only a specific test or module (probably wouldn't sweat it if this doesn't make it into the initial test release, but seems small enough to squeeze in).
* [x] Document the use of `ember nw:test`
* [x] Make sure the functionality works on Windows too
  * Technically, the tests do run on Windows. However, there is a problem with processing the output of child processes (`nw`), so the test output can't be parsed by Testem. Tracking this in #32.

**Comment by sedouard** [comment]
Hey @brzpegasus! Check your [gitter](http://gitter.im) had some questions for you

**Comment by brzpegasus** [comment]
@sedouard I left a reply there this morning.
